// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMvbWyCcRvJ8jfWXKN_CzvbLg2x6H7G3c',
    appId: '1:129788942359:android:87b51751fda0c52c',
    messagingSenderId: '129788942359',
    projectId: 'duma-5832e',
    databaseURL: 'https://duma-5832e.firebaseio.com',
    storageBucket: 'duma-5832e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoXLi7a-9t8wUIcwkP4NQgcWPzmAh5FkU',
    appId: '1:129788942359:ios:5946037118187eb642e452',
    messagingSenderId: '129788942359',
    projectId: 'duma-5832e',
    databaseURL: 'https://duma-5832e.firebaseio.com',
    storageBucket: 'duma-5832e.appspot.com',
    androidClientId: '129788942359-2ijpisftddipe2aqgda5qmfialrv5m4r.apps.googleusercontent.com',
    iosClientId: '129788942359-ovjamlf451k3er5us1lb8v826dbsndg9.apps.googleusercontent.com',
    iosBundleId: 'africa.duma.dumafin',
  );

}